//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace MWM_Assignment_New
{


    public partial class _Default
    {

        /// <summary>
        /// rptFeatured control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Repeater rptFeatured;

        /// <summary>
        /// txtContactName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtContactName;

        /// <summary>
        /// rfvContactName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvContactName;

        /// <summary>
        /// txtContactEmail control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtContactEmail;

        /// <summary>
        /// rfvContactEmail control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvContactEmail;

        /// <summary>
        /// revContactEmail control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RegularExpressionValidator revContactEmail;

        /// <summary>
        /// txtContactSubject control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtContactSubject;

        /// <summary>
        /// rfvContactSubject control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvContactSubject;

        /// <summary>
        /// txtContactMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtContactMessage;

        /// <summary>
        /// rfvContactMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvContactMessage;

        /// <summary>
        /// btnSendInquiry control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnSendInquiry;

        /// <summary>
        /// lblContactStatus control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblContactStatus;
    }
}
