//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace MWM_Assignment_New.Admin
{


    public partial class ManageCoupons
    {

        /// <summary>
        /// txtCode control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtCode;

        /// <summary>
        /// rfvCode control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvCode;

        /// <summary>
        /// txtDescription control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtDescription;

        /// <summary>
        /// ddlDiscountType control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlDiscountType;

        /// <summary>
        /// txtDiscountValue control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtDiscountValue;

        /// <summary>
        /// rfvDiscountValue control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvDiscountValue;

        /// <summary>
        /// rvDiscountValue control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RangeValidator rvDiscountValue;

        /// <summary>
        /// chkIsActive control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlInputCheckBox chkIsActive;

        /// <summary>
        /// btnAddCoupon control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnAddCoupon;

        /// <summary>
        /// lblCouponAdminMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblCouponAdminMessage;

        /// <summary>
        /// gvCoupons control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvCoupons;
    }
}
